In [1]:
import numpy as np
import pandas as pd

# Removes the limit for the number of displayed columns
pd.set_option("display.max_columns", None)
# Sets the limit for the number of displayed rows
pd.set_option("display.max_rows", 100)

# import and filter warnings
import warnings
warnings.filterwarnings("ignore")

#### Declaration

In [2]:
# Declare vectors u, v
u = np.array([2,4,6,8])
v = np.array([1,0,0,2])

#### Addition

In [3]:
# vector addition
u_plus_v = u + v
u_plus_v

array([ 3,  4,  6, 10])

#### Multiply by scalar

In [6]:
3 * u

array([ 6, 12, 18, 24])

#### Vector x Vector multiplication (dot product)

In [5]:
# element-wise multiplication
u * v

array([ 2,  0,  0, 16])

In [8]:
# vectors should have the same size
def vector_vector_multiplication(a, b):
    assert a.shape[0] == b.shape[0]

    n = a.shape[0]

    result = 0.0

    for i in range(n):
        result = result + a[i] * b[i]

    return result

In [9]:
vector_vector_multiplication(u, v)

np.float64(18.0)

In [10]:
# use numpy inbuilt function for dot product
u.dot(v)

np.int64(18)

#### Matrix vector multiplication
- Transpose U and multiply by v

In [26]:
def matrix_vector_multiplication(A, b):
    assert A.shape[1] == b.shape[0]

    num_rows = A.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(A[i], b)

    return result

In [30]:
# matrix_vector_multiplication example
A = np.array([[1,2,3], [4,5,6]])
b = np.array([7,8,9])
matrix_vector_multiplication(A, b)

array([ 50., 122.])

In [33]:
# using Numpy inbuilt function
A.dot(b)

array([ 50, 122])

### Matrix x Matrix multiplication

In [31]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [38]:
# Example for matrix_matrix_multiplication by 2x3, 3x2 matrices
# declare 2x3 matrix
mat1 = np.array([[1,2,3], [4,5,6]])

# declare 3x2 matrix
mat2 = np.array([[7,8], [9,10], [11,12]])

In [37]:
# Result should be 2x2 matrix
matrix_matrix_multiplication(mat1, mat2)

array([[ 58.,  64.],
       [139., 154.]])

### Identity Matrix
- Diagonal is 1, rest are 0
- denoted by I

In [40]:
# numpy inbuilt function to create identity matrix
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
# multiply identity matrix with another matrix
A = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
I.dot(A)

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

### Inverse Matrix
- Denoted by A^-1
- Array must be square

In [46]:
a = np.array([[1,2,3], [4,5,6], [7,8,10]])

In [47]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [48]:
np.linalg.inv(a)

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])