In [45]:
import numpy as np
import pandas as pd

# Removes the limit for the number of displayed columns
pd.set_option("display.max_columns", None)
# Sets the limit for the number of displayed rows
pd.set_option("display.max_rows", 100)

# import and filter warnings
import warnings
warnings.filterwarnings("ignore")

### Single dimensional arrays

In [2]:
# Fills zeros in an array of size 5
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
# Fills ones in an array of size 5
np.ones(5)

array([1., 1., 1., 1., 1.])

In [4]:
# Fills array of 10 elements with 2.5 as value
np.full(10,2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
# create a numpy array with values from 1 to 5
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
# access number 3 in the array
a[2]

np.int64(3)

In [10]:
# change the value in position 2 to 42 from 3
a[2] = 42
a

array([ 1,  2, 42,  4,  5])

In [11]:
# range function to print values from 0 to 10
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# linspace function to create a range between 0 and 1 with 25 values
np.linspace(0,1,25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

### Multidimensional arrays

In [13]:
# 5x2 array with all values as 1
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
# create a multidimensional array 3x3
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
# access value 5 from b
b[1,1]

np.int64(5)

In [16]:
# assign 20 to position of 5
b[1,1] = 20
b

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [18]:
# print entire second row
b[1]

array([ 4, 20,  6])

In [17]:
# print entire second row
b[1,:]

array([ 4, 20,  6])

In [19]:
# print entire second column
b[:,1]

array([ 2, 20,  8])

In [20]:
# print entire second column
b[1]

array([ 4, 20,  6])

In [21]:
# print all rows
b[:]

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [22]:
#### Randomly generated arrays
np.random.randn(5, 2)

array([[ 0.31172369,  0.8708946 ],
       [ 1.19401163, -0.66304069],
       [ 0.84810496,  0.8743256 ],
       [ 1.02976053,  0.20466172],
       [-1.16724223, -0.66920477]])

In [23]:
# set seed and generate random array
np.random.seed(42)
np.random.randn(5, 2)

array([[ 0.49671415, -0.1382643 ],
       [ 0.64768854,  1.52302986],
       [-0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004]])

In [26]:
# print again the same array by using the same seed
np.random.seed(42)
np.random.randn(5, 2)

array([[ 0.49671415, -0.1382643 ],
       [ 0.64768854,  1.52302986],
       [-0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473],
       [-0.46947439,  0.54256004]])

In [27]:
# generate random numbers from random distribution
np.random.randn(5, 2)

array([[-0.46341769, -0.46572975],
       [ 0.24196227, -1.91328024],
       [-1.72491783, -0.56228753],
       [-1.01283112,  0.31424733],
       [-0.90802408, -1.4123037 ]])

In [28]:
# print random numbers by 10
10 * np.random.randn(5, 2)

array([[ 14.65648769,  -2.257763  ],
       [  0.67528205, -14.24748186],
       [ -5.44382725,   1.1092259 ],
       [-11.50993577,   3.75698018],
       [ -6.0063869 ,  -2.9169375 ]])

In [29]:
# generate 10 random integers between 1 and 100
np.random.randint(1,100,10)

array([84, 92, 60, 71, 44,  8, 47, 35, 78, 81])

### Element-wise operations

In [31]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [32]:
# Add 1 to all numbers
a + 1

array([1, 2, 3, 4, 5])

In [33]:
# multiply all numbers by 2
a * 2

array([0, 2, 4, 6, 8])

In [35]:
# create another array
b = np.arange(5,10)
b

array([5, 6, 7, 8, 9])

In [36]:
# add two arrays
a + b

array([ 5,  7,  9, 11, 13])

In [37]:
# multiply two arrays
a * b

array([ 0,  6, 14, 24, 36])

### Comparison operations

In [38]:
# check if array elements greater than 3
a > 3

array([False, False, False, False,  True])

In [39]:
b > 2

array([ True,  True,  True,  True,  True])

In [41]:
# compare 2 arrays
a > b

array([False, False, False, False, False])

In [44]:
# check which eleemnts in b are greater than 6
b[b > 6]

array([7, 8, 9])

### Summarising operations

In [46]:
a

array([0, 1, 2, 3, 4])

In [47]:
# maximum value in array
a.max()

np.int64(4)

In [50]:
# minimum value in array
a.min()

np.int64(0)

In [49]:
b.max()

np.int64(9)

In [51]:
# array sum
# create a multidimensional array 3x3
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
b.sum()

np.int64(45)

In [53]:
# average
b.mean()

np.float64(5.0)

In [54]:
# standard deviation
b.std()

np.float64(2.581988897471611)

In [55]:
a.mean()

np.float64(2.0)

In [56]:
a.std()

np.float64(1.4142135623730951)